- hosts: localhost
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - name: Dev tasks
      import_tasks: tasks/dev/_main.yml
      tags: ["dev"]
    - name: Shell tasks
      import_tasks: tasks/shell/_main.yml
      tags: ["shell"]