- name: include variables
  include_vars: vars/nvm.yml

- name: install nvm latest
  git:
    repo: https://github.com/creationix/nvm.git
    dest: "{{ nvm_install_path }}"

- name: install Node {{ nvm_node_version }}
  shell: ". ./nvm.sh && nvm install {{ node_version }}"
  args:
    chdir: "{{ nvm_install_path }}"
