---
- name: Ensure apt cache is up to date
  apt:
    update_cache: yes
  become: true

- name: Install development packages necessary for building Python
  apt:
    pkg: "{{ pyenv_debian_packages }}"
    state: present
  become: true