- name: include variables
  include_vars: vars/pyenv.yml

- name: ensure apt cache is up to date
  apt:
    update_cache: true
  become: true

- name: install development packages necessary for setting up pyenv
  apt:
    pkg: "{{ pyenv_debian_packages }}"
    state: present
  become: true

- name: install PyEnv
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: "{{ pyenv_path }}"
    update: "{{ pyenv_update_git_install }}"
